version: '3'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: "drf"
      POSTGRES_USER: "drf_user"
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
  django:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - postgres