# Generated by Django 4.1.2 on 2022-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinalbum',
            name='serial_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер в альбоме'),
        ),
    ]
